sudo: false

language: node_js

node_js:
  - "4"
  - "10"
  
cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
    
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
